In [98]:
import numpy as np 
import pandas as pd 
import random

In [124]:
class_prices = np.array([10, 20, 10, 5, 10, 30, 2, 23, 14, 31], dtype=np.int16).reshape(1, 10)
classes = np.array(["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"])
bundles = {
    'B1':["a", "b", "c"],
    'B2':["f", "h", "h"],
    'B3':["j", "j", "j"],
    'B4':["d", "e", "i"],
    'B5':["f", "f", "g"],
    'B6':["a", "e", "i"],
    'B7':["b", "c", "d"],
    'B8':["g", "i", "j"]
}
bundles_discounts = {
    'B1': 0.1,
    'B2': 0.2,
    'B3':0.25,
    'B4':0.05,
    'B5':0.15,
    'B6': 0.35,
    'B7': 0.1,
    'B8':0.33
}

In [132]:
bundle_discounts_arr = (1 - np.fromiter(bundles_discounts.values(), dtype=float)).reshape(8, 1)
bundle_discounts_arr

array([[0.9 ],
       [0.8 ],
       [0.75],
       [0.95],
       [0.85],
       [0.65],
       [0.9 ],
       [0.67]])

In [143]:
# sorted bundle discounts (descending)
bundles_sorted_indices = np.argsort(np.fromiter(bundles_discounts.values(), dtype=float))
bundles_sorted_indices

array([3, 0, 6, 4, 1, 2, 7, 5])

In [125]:
basket_product_number = np.random.random_integers(1, 20, size=(10, ))
basket_product_number

array([17, 12, 16, 12, 13, 11,  3,  9, 16, 10])

In [67]:
from collections import Counter

def get_bundle_vector(bundle):
    vector = []
    for class_ in classes:
        if class_ in bundle:
            vector.append(Counter(bundle)[class_])
        else:
            vector.append(0)
    return vector

In [137]:
bundle_dict = {k: get_bundle_vector(v) for k, v in bundles.items()}
bundle_dict

{'B1': [1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 'B2': [0, 0, 0, 0, 0, 1, 0, 2, 0, 0],
 'B3': [0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
 'B4': [0, 0, 0, 1, 1, 0, 0, 0, 1, 0],
 'B5': [0, 0, 0, 0, 0, 2, 1, 0, 0, 0],
 'B6': [1, 0, 0, 0, 1, 0, 0, 0, 1, 0],
 'B7': [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
 'B8': [0, 0, 0, 0, 0, 0, 1, 0, 1, 1]}

In [83]:
bundle_matrix = pd.DataFrame.from_dict(bundle_dict, orient='index').values
bundle_matrix

array([[1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [0, 0, 0, 1, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 2, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 1]])

In [144]:
# if discount if bigger bungle goes first (descending)
bundle_sorted_matrix = bundle_matrix[bundles_sorted_indices][:]
bundle_sorted_matrix

array([[0, 0, 0, 1, 1, 0, 0, 0, 1, 0],
       [1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 1],
       [1, 0, 0, 0, 1, 0, 0, 0, 1, 0]])

In [145]:
bundle_discounts_arr = (1 - np.fromiter(bundles_discounts.values(), dtype=float)).reshape(8, 1)
bundle_discounts_arr

array([[0.9 ],
       [0.8 ],
       [0.75],
       [0.95],
       [0.85],
       [0.65],
       [0.9 ],
       [0.67]])

In [108]:
# WHY WE NEED THIS? 
# prices for ALL classes with discounts  
# one row = one discount value 
# one column = one class
discounted_prices = bundle_discounts_arr * class_prices
discounted_prices

array([[ 9.  , 18.  ,  9.  ,  4.5 ,  9.  , 27.  ,  1.8 , 20.7 , 12.6 ,
        27.9 ],
       [ 8.  , 16.  ,  8.  ,  4.  ,  8.  , 24.  ,  1.6 , 18.4 , 11.2 ,
        24.8 ],
       [ 7.5 , 15.  ,  7.5 ,  3.75,  7.5 , 22.5 ,  1.5 , 17.25, 10.5 ,
        23.25],
       [ 9.5 , 19.  ,  9.5 ,  4.75,  9.5 , 28.5 ,  1.9 , 21.85, 13.3 ,
        29.45],
       [ 8.5 , 17.  ,  8.5 ,  4.25,  8.5 , 25.5 ,  1.7 , 19.55, 11.9 ,
        26.35],
       [ 6.5 , 13.  ,  6.5 ,  3.25,  6.5 , 19.5 ,  1.3 , 14.95,  9.1 ,
        20.15],
       [ 9.  , 18.  ,  9.  ,  4.5 ,  9.  , 27.  ,  1.8 , 20.7 , 12.6 ,
        27.9 ],
       [ 6.7 , 13.4 ,  6.7 ,  3.35,  6.7 , 20.1 ,  1.34, 15.41,  9.38,
        20.77]])

In [147]:
import copy 

basket_copy = copy.deepcopy(basket_product_number)

total_cost = 0 
next_flag = False 
for indx, bundle in enumerate(bundle_sorted_matrix):
    while not next_flag:
        for b in range(len(bundle)):
            # print(indx, bundle[b], basket_copy[b])
            if bundle[b] > basket_copy[b]:
                print('Bundle is not usable')
                next_flag = True 
                break 
        if not next_flag:
            total_cost += sum(bundle * discounted_prices[0].T)
            basket_copy -= bundle
            # print(f"N: {indx} | {total_cost}")
    next_flag = False 

print(total_cost)

            

Bungle is not usable
Bungle is not usable
Bungle is not usable
Bungle is not usable
Bungle is not usable
Bungle is not usable
Bungle is not usable
Bungle is not usable
1467.9
