# KD-Tree

* each level of the tree organizes the data along different dimension (cycling through each dimention repeatedly). 


In [8]:
import numpy as np 
import pandas as pd 
import random 

In [9]:
number_of_users = 10 
number_of_options = 8

In [10]:
np.random.seed(10)

data = np.random.randint(0, 2, size=(number_of_users, number_of_options))
data, data.shape

(array([[1, 1, 0, 1, 0, 1, 1, 0],
        [1, 1, 0, 1, 1, 0, 0, 1],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [1, 1, 0, 0, 1, 0, 0, 1],
        [0, 0, 0, 1, 1, 0, 1, 1],
        [1, 1, 1, 0, 1, 0, 0, 0],
        [0, 1, 0, 1, 1, 1, 0, 1],
        [0, 1, 1, 0, 1, 0, 0, 1],
        [0, 0, 0, 1, 1, 0, 0, 0],
        [1, 0, 1, 1, 0, 1, 1, 0]]),
 (10, 8))

In [11]:
pd_data = pd.DataFrame(
    data=data, 
    index=[i for i in range(number_of_users)],
    columns=['f'+str(j) for j in range(number_of_options)]
)
pd_data

f0  f1  f2  f3  f4  f5  f6  f7
0   1   1   0   1   0   1   1   0
1   1   1   0   1   1   0   0   1
2   0   0   0   0   0   1   0   0
3   1   1   0   0   1   0   0   1
4   0   0   0   1   1   0   1   1
5   1   1   1   0   1   0   0   0
6   0   1   0   1   1   1   0   1
7   0   1   1   0   1   0   0   1
8   0   0   0   1   1   0   0   0
9   1   0   1   1   0   1   1   0

In [12]:
from sklearn.neighbors import KDTree

ModuleNotFoundError: No module named 'sklearn'

In [58]:
# leaf_size 
# Number of points at which to switch to brute-force.
# Changing leaf_size will not affect the results of a query, 
# but can significantly impact the speed of a query
# and the memory required to store the constructed tree.
kd_tree = KDTree(data, leaf_size=number_of_options)

In [1]:
new_user = np.random.randint(0, 2, size=(1, number_of_options))
new_user

NameError: name 'np' is not defined

In [59]:
dist, ind = kd_tree.query(data[:1], k=3)
ind 

array([[0, 9, 1]])

In [60]:
# use euclidean_distances to find similarities 
dist

array([[0.        , 1.41421356, 2.        ]])

In [61]:
from sklearn.metrics.pairwise import cosine_similarity

cos_similarities = np.zeros((data.shape[0],))
for i in range(data.shape[0]):
    if i == data.shape[0] - 1:
        cos_similarities[i] = cosine_similarity(data[:1], data[i:])
        print(f"User {i}\tSimilarity: {round(cos_similarities[i], 4)}")
        break 
    cos_similarities[i] = cosine_similarity(data[:1], data[i:i+1])
    print(f"User {i}\tSimilarity: {round(cos_similarities[i], 4)}")

User 0	Similarity: 1.0
User 1	Similarity: 0.6
User 2	Similarity: 0.4472
User 3	Similarity: 0.4472
User 4	Similarity: 0.4472
User 5	Similarity: 0.4472
User 6	Similarity: 0.6
User 7	Similarity: 0.2236
User 8	Similarity: 0.3162
User 9	Similarity: 0.8


In [62]:
from sklearn.metrics.pairwise import euclidean_distances

euc_similarities = np.zeros((data.shape[0],))
for i in range(data.shape[0]):
    if i == data.shape[0] - 1:
        euc_similarities[i] = euclidean_distances(data[:1], data[i:])
        print(f"User {i}\tSimilarity: {round(euc_similarities[i], 4)}")
        break 
    euc_similarities[i] = euclidean_distances(data[:1], data[i:i+1])
    print(f"User {i}\tSimilarity: {round(euc_similarities[i], 4)}")

User 0	Similarity: 0.0
User 1	Similarity: 2.0
User 2	Similarity: 2.0
User 3	Similarity: 2.2361
User 4	Similarity: 2.2361
User 5	Similarity: 2.2361
User 6	Similarity: 2.0
User 7	Similarity: 2.6458
User 8	Similarity: 2.2361
User 9	Similarity: 1.4142


In [77]:
user_ids = [i for i in range(number_of_users)]
custome_answers = [
    'Engineering', 
    'Mathematics',
    'Computer Science', 
    'Cooking', 
    'Physics', 
    'Nanotechnology', 
    'Biology', 
    'Genetics', 
    'entertainment',
    'music'
]
pd_words = pd.DataFrame(data=user_ids, columns=['ID'])
pd_words = pd.concat([pd_words, pd.DataFrame(custome_answers, columns=['answers'])], axis=1)
pd_words

ID           answers
0   0       Engineering
1   1       Mathematics
2   2  Computer Science
3   3           Cooking
4   4           Physics
5   5    Nanotechnology
6   6           Biology
7   7          Genetics
8   8     entertainment
9   9             music