In [1]:
import pandas as pd

In [2]:
import numpy as np

arr = np.random.randint(0, 10, size=(5, 3))
print(arr)

[[9 5 9]
 [1 9 4]
 [9 1 5]
 [7 1 4]
 [7 4 0]]


In [3]:
# Создание фрейма - просто вызвать конструктор
df = pd.DataFrame(data=arr)
# Фреймы удобнее отображать с помощью встроенных средств Jupyter
df

0  1  2
0  9  5  9
1  1  9  4
2  9  1  5
3  7  1  4
4  7  4  0

In [5]:
# Task 1 
arr = np.random.randint(0, 10, size=(5, 3))
df = pd.DataFrame(data=arr, columns=['col_1', 'col_2', 'col_3'], index=['A', 'B', 'C', 'D', 'E'])
df

col_1  col_2  col_3
A      6      5      2
B      8      4      4
C      8      8      8
D      8      6      7
E      1      1      9

In [6]:
# Создается словарь, в котором ключи будут названиями колонок,
#   а значения - данные по этим колонкам
data = {
    'test_1_mark': [4.6, 3.8, 5.0, 4.5],
    'test_2_mark': [5.0, 3.9, 4.7, 4.5]
}

pd.DataFrame(data)

test_1_mark  test_2_mark
0          4.6          5.0
1          3.8          3.9
2          5.0          4.7
3          4.5          4.5

In [7]:
# Создается список записей, каждая запись представлена словарем
# В словаре ключи - названия колонок
# При создании фрейма pandas просмотри все возможные ключи словарей в списке
#   и создаст колонок по их названиям
data = [
    {
        'test_1_mark': 4.6,
        'test_2_mark': 5.0
    },
    {
        'test_1_mark': 3.8,
        'test_2_mark': 3.9
    },
    {
        'test_1_mark': 5.0
    },
]

pd.DataFrame(data)

test_1_mark  test_2_mark
0          4.6          5.0
1          3.8          3.9
2          5.0          NaN

In [8]:
df = pd.DataFrame({'A': 1.,
                   'B': pd.Timestamp('20130102'),
                   'C': np.array([2.] * 4, dtype='float32'),
                   'D': np.array([3] * 4, dtype='int32'),
                   'E': pd.Categorical(["test", "train", "test", "train"]),
                   'F': 'foo'})
df

A          B    C  D      E    F
0  1.0 2013-01-02  2.0  3   test  foo
1  1.0 2013-01-02  2.0  3  train  foo
2  1.0 2013-01-02  2.0  3   test  foo
3  1.0 2013-01-02  2.0  3  train  foo

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   A       4 non-null      float64       
 1   B       4 non-null      datetime64[ns]
 2   C       4 non-null      float32       
 3   D       4 non-null      int32         
 4   E       4 non-null      category      
 5   F       4 non-null      object        
dtypes: category(1), datetime64[ns](1), float32(1), float64(1), int32(1), object(1)
memory usage: 356.0+ bytes


In [10]:
df = pd.DataFrame(
    data=np.random.randint(-10, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)

# Функция получения первых записей фрейма
# Аргументом задается количество выводимых данных
#   Если не задано - 5 по-умолчанию
df.head(4)

x1  x2  x3
0  -1  -2   4
1  -9  -2  -2
2   5   3   3
3  -5   7  -7

In [11]:
# Функция получения последних записей фрейма
# Аргументом задается количество выводимых данных
#   Если не задано - 5 по-умолчанию
df.tail(4)

x1  x2  x3
11 -10  -3   8
12   0  -1  -6
13  -2   6   1
14  -3  -1  -5

In [12]:
# Функция отображения основной информации о фрейме:
#   Количество записей
#   Типы колонок
#   Количество ненулевых значений
#   Тип индекса
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x1      15 non-null     int64
 1   x2      15 non-null     int64
 2   x3      15 non-null     int64
dtypes: int64(3)
memory usage: 488.0 bytes


In [13]:
# Функция отображения статистики по численным колонкам
df.describe()

x1         x2         x3
count  15.000000  15.000000  15.000000
mean   -1.800000   0.533333  -1.000000
std     5.361237   5.054936   6.023762
min   -10.000000  -8.000000 -10.000000
25%    -5.500000  -2.000000  -6.500000
50%    -2.000000  -1.000000   0.000000
75%     2.000000   5.000000   3.500000
max     8.000000   8.000000   8.000000

In [14]:
# Атрибут получения индексов фрейма
df.index

RangeIndex(start=0, stop=15, step=1)

In [15]:
# Или чтобы представить в виде списка
list(df.index)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [16]:
# Атрибут получения имен колонок фрейма
df.columns

Index(['x1', 'x2', 'x3'], dtype='object')

In [17]:
df.shape

(15, 3)

In [18]:
df.to_numpy()

array([[ -1,  -2,   4],
       [ -9,  -2,  -2],
       [  5,   3,   3],
       [ -5,   7,  -7],
       [ -8,   8,   0],
       [  8,   1,   6],
       [ -6,  -2,   2],
       [  1,  -8,  -7],
       [  4,   4, -10],
       [  3,   6,   7],
       [ -4,  -8,  -9],
       [-10,  -3,   8],
       [  0,  -1,  -6],
       [ -2,   6,   1],
       [ -3,  -1,  -5]])

In [19]:
# Получение транспонированного представления
# Колонки -> ряды, ряды -> колонки
df.T

# (*) Транспонирование вряд ли часто понадобится при анализе, но учитывать стоит

0   1   2   3   4   5   6   7   8   9   10  11  12  13  14
x1  -1  -9   5  -5  -8   8  -6   1   4   3  -4 -10   0  -2  -3
x2  -2  -2   3   7   8   1  -2  -8   4   6  -8  -3  -1   6  -1
x3   4  -2   3  -7   0   6   2  -7 -10   7  -9   8  -6   1  -5

In [20]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    columns=['x1', 'x2', 'x3']
)

df

x1  x2  x3
0   7   0   2
1   8   3   8
2   0   9   7
3   7   4   9
4   9   4   6

In [22]:
print(f"Column 'x1':\n{df['x1']}\n")
print(type(df['x1']))

Column 'x1':
0    7
1    8
2    0
3    7
4    9
Name: x1, dtype: int64

<class 'pandas.core.series.Series'>


In [23]:
data = {
    'feature1': np.arange(15),
    'feature2': np.linspace(0, 10, 15),
    'feature3': 'string',
}
df = pd.DataFrame(data, index=list('ABCDEFGHIJKLMNO'))
df.head()

feature1  feature2 feature3
A         0  0.000000   string
B         1  0.714286   string
C         2  1.428571   string
D         3  2.142857   string
E         4  2.857143   string

In [24]:
df.iloc[2]

feature1          2
feature2    1.42857
feature3     string
Name: C, dtype: object

In [25]:
df.loc['C']

feature1          2
feature2    1.42857
feature3     string
Name: C, dtype: object

In [26]:
df.iloc[2, 1]

1.4285714285714286

In [27]:
df.loc['C', 'feature2']

1.4285714285714286

In [28]:
# Task 2 
data = {
    'feature1': np.arange(15),
    'feature2': np.linspace(0, 10, 15),
    'feature3': 'string',
}
df = pd.DataFrame(data, index=list('ABCDEFGHIJKLMNO'))
df.head()

feature1  feature2 feature3
A         0  0.000000   string
B         1  0.714286   string
C         2  1.428571   string
D         3  2.142857   string
E         4  2.857143   string

In [29]:
df.loc['C':'I', ['feature1', 'feature2']]

feature1  feature2
C         2  1.428571
D         3  2.142857
E         4  2.857143
F         5  3.571429
G         6  4.285714
H         7  5.000000
I         8  5.714286

In [31]:
df.iloc[2:9, [0, 2]]

feature1 feature3
C         2   string
D         3   string
E         4   string
F         5   string
G         6   string
H         7   string
I         8   string

In [32]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   3   4   6
1   7   0   9
2   9   6   6

In [33]:
df['x1'] > 5

0     False
1      True
2      True
3      True
4      True
5      True
6     False
7      True
8     False
9      True
10    False
11    False
12    False
13     True
14     True
Name: x1, dtype: bool

In [34]:
mask = df['x1'] > 5
df[mask]

# Или df[df['x1'] > 5]

x1  x2  x3
1    7   0   9
2    9   6   6
3    7   9   4
4    6   8   3
5    6   1   3
7    6   5   4
9    8   3   0
13   9   0   5
14   7   3   8

In [35]:
df[~(df['x1'] > 5)]

x1  x2  x3
0    3   4   6
6    0   9   0
8    1   6   8
10   3   5   4
11   4   6   9
12   5   3   5

In [36]:
# Task 3
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   9   4   2
1   8   0   0
2   8   0   1

In [48]:
masked_df = df[(df['x1'] > 3) & (df['x3'] < 8)]
masked_df.loc[:, ['x1', 'x2']]

x1  x2
0    9   4
1    8   0
2    8   0
4    5   8
5    5   4
10   8   2
14   7   0

In [49]:
# Task 4 
df = pd.DataFrame(
    [[1, 2, 6], [5, 1, 1], [8, 4, 6], [4, 1, 1], [9, 9, 0], [-1, 2, 1], [5, 5, 5]],
    columns = ['x1', 'x2', 'x3']
)
df.query('x1 > x3')

x1  x2  x3
1   5   1   1
2   8   4   6
3   4   1   1
4   9   9   0

In [50]:
df[df['x1'] > df['x3']]

x1  x2  x3
1   5   1   1
2   8   4   6
3   4   1   1
4   9   9   0

In [51]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   4   5   2
1   5   1   4
2   6   2   3

In [52]:
# Создать новую колонку можно по аналогии с новым ключем в словаре
# Сложение нескольких Series и запись в новую колонку
df['x1+x2'] = df['x1'] + df['x2']
df.head(3)

x1  x2  x3  x1+x2
0   4   5   2      9
1   5   1   4      6
2   6   2   3      8

In [53]:
# Поэлементное умножение
df['x1*x3'] = df['x1'] * df['x3']
df.head(3)

x1  x2  x3  x1+x2  x1*x3
0   4   5   2      9      8
1   5   1   4      6     20
2   6   2   3      8     18

In [54]:
# Взятие среднего по колонке (метод Series.mean())
df['x1'].mean()

4.4

In [55]:
# Использование функций numpy для работы с колонками
df['x2_exp'] = np.exp(df['x2'])
df.head(3)

x1  x2  x3  x1+x2  x1*x3      x2_exp
0   4   5   2      9      8  148.413159
1   5   1   4      6     20    2.718282
2   6   2   3      8     18    7.389056

In [56]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(3, 3)), 
    columns=['x1', 'x2', 'x3']
)
df

x1  x2  x3
0   9   3   5
1   8   2   1
2   0   8   1

In [57]:
# Обязательно требование к функции - один аргумент
# Эта функция будет передана в apply() и pandas
#   будет вызывать ее и передавать в нее 
#   по одному элементу из ряда
# Возвращать функция должна результат операции над элементом
def my_func(x):
    print(type(x))
    print(x)
    return x*2

df['result'] = df['x1'].apply(my_func)
df

<class 'int'>
9
<class 'int'>
8
<class 'int'>
0


x1  x2  x3  result
0   9   3   5      18
1   8   2   1      16
2   0   8   1       0

In [58]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   8   5   2
1   7   6   2
2   8   0   0

In [59]:
# Методу передается в аргумент columns словарь, 
#   в котором ключи - имена колонок,
#   значения - новые имена для переименования
df.rename(
    columns={
        'x1': 'new_name_for_x1',
        'x3': 'that_not_x3' 
    },
    inplace=True
)
df.head(3)

new_name_for_x1  x2  that_not_x3
0                8   5            2
1                7   6            2
2                8   0            0

In [65]:
df_renamed = df.rename(columns={
    'x1': 'new_name_for_x1',
    'x3': 'that_not_x3'
})

In [78]:
# Task 5 
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    index=['A', 'B', 'C', 'D', 'E'], 
    columns=['x1', 'x2', 'x3']
)
df

x1  x2  x3
A   0   6   4
B   4   2   5
C   8   2   8
D   8   6   1
E   8   9   9

In [76]:
df.rename(
    columns={
        'x1': 'new1',
        'x2': 'new2',
        'x3': 'new3'
    },
    index={
        'A': 'indA',
        'B': 'indB',
        'C': 'indC', 
        'D': 'indD',
        'E': 'indE'
    },
    inplace=True
)
df.head()

new1  new2  new3
indA     9     5     7
indB     3     0     4
indC     4     8     8
indD     0     0     3
indE     1     4     5

In [79]:
df.rename(
    index={
        'A': 'indA',
        'C': 'indC',
    },
    columns={
        'x1': 'new1',
        'x3': 'new3' 
    },
    inplace=True
)

df

new1  x2  new3
indA     0   6     4
B        4   2     5
indC     8   2     8
D        8   6     1
E        8   9     9

In [80]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.head(3)

x1  x2  x3
0   4   1   1
1   3   1   3
2   3   8   9

In [81]:
df.drop(columns=['x2'], inplace=True)
df.head(3)

x1  x3
0   4   1
1   3   3
2   3   9

In [82]:
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(5, 3)), 
    columns=['x1', 'x2', 'x3']
)
df.iloc[0, :2] = np.nan
df.iloc[2, 1:] = np.nan

df

x1   x2   x3
0  NaN  NaN  7.0
1  0.0  0.0  3.0
2  1.0  NaN  NaN
3  1.0  9.0  9.0
4  8.0  0.0  2.0

In [83]:
df.isna()

x1     x2     x3
0   True   True  False
1  False  False  False
2  False   True   True
3  False  False  False
4  False  False  False

In [84]:
df.isna().sum()

x1    1
x2    2
x3    1
dtype: int64

In [85]:
df['x2'].fillna(3, inplace=True)
df

x1   x2   x3
0  NaN  3.0  7.0
1  0.0  0.0  3.0
2  1.0  3.0  NaN
3  1.0  9.0  9.0
4  8.0  0.0  2.0

In [86]:
df = pd.DataFrame({
    'col1': ['high', 'high', 'low', 'med', 'low', 'low', 'med', 'low', 'low', 'high'],
    'col2': [0, 1, 1, 2, 3, 1, 1, 2, 2, 2]
})
df

col1  col2
0  high     0
1  high     1
2   low     1
3   med     2
4   low     3
5   low     1
6   med     1
7   low     2
8   low     2
9  high     2

In [87]:
# Метод DataFrame.nunique() позволяет вывести 
#   количество уникальных значений в каждой колонке
# Результат - Series с индексами - названиями колонок
df.nunique()

col1    3
col2    4
dtype: int64

In [88]:
# Метод Series.value_counts() показывает уникальные значения в ряду
#   и указывает их количество
df['col1'].value_counts()

low     5
high    3
med     2
Name: col1, dtype: int64

In [89]:
# Результат - Series с индексами - уникальными значениями
df['col2'].value_counts()

2    4
1    4
3    1
0    1
Name: col2, dtype: int64

In [90]:
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6])),
                  index=['mouse', 'rabbit'],
                  columns=['col_one', 'col_two', 'col_three'])
df

col_one  col_two  col_three
mouse         1        2          3
rabbit        4        5          6

In [91]:
# Отфильтровать по именам колонок
# Аналогично df[['col_one', 'col_three']]
df.filter(items=['col_one', 'col_three'], axis='columns')

col_one  col_three
mouse         1          3
rabbit        4          6

In [92]:
# Отфильтровать по регулярному выражению
# Оставить только те колонки, которые оканчиваются на букву "o"
df.filter(regex='o$', axis='columns')

col_two
mouse         2
rabbit        5

In [93]:
# Task 6 
df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6], [7, 8, 9])),
                  index=['dog in house', 'cat in house', 'pig in farm'],
                  columns=['x1', 'x2', 'x3'])
df

x1  x2  x3
dog in house   1   2   3
cat in house   4   5   6
pig in farm    7   8   9

In [96]:
df.filter(like='house', axis='rows')

x1  x2  x3
dog in house   1   2   3
cat in house   4   5   6

In [97]:
df = pd.DataFrame({
    'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
    'col2': [2, 1, 9, 8, 7, 4],
    'col3': [0, 1, 9, 4, 2, 3],
    'col4': ['a', 'B', 'c', 'D', 'e', 'F']
}, index=['A', 'B', 'C', 'D', 'E', 'F'])
df

col1  col2  col3 col4
A    A     2     0    a
B    A     1     1    B
C    B     9     9    c
D  NaN     8     4    D
E    D     7     2    e
F    C     4     3    F

In [98]:
# Отсортируем записи колонки col2
# Именно поэтому в axis ставится rows, так как
#   операция производится в колонке по каждому ряду
df.sort_values(by='col2', axis='rows')

col1  col2  col3 col4
B    A     1     1    B
A    A     2     0    a
F    C     4     3    F
E    D     7     2    e
D  NaN     8     4    D
C    B     9     9    c

In [99]:
# Task 7
df = pd.DataFrame(
    np.random.randint(0, 20, size=(5, 5)), 
    columns=['col1', 'col2', 'col3', 'col4', 'col5']
)
df

col1  col2  col3  col4  col5
0     2     6     1     3     8
1     3    19    16    18     7
2    16    11    10     7     8
3     8    16     5    14     7
4     5    17    19    18     3

In [100]:
df.sort_values(by=3, axis='columns', ascending=False)

col2  col4  col1  col5  col3
0     6     3     2     8     1
1    19    18     3     7    16
2    11     7    16     8    10
3    16    14     8     7     5
4    17    18     5     3    19

In [101]:
df = pd.DataFrame({
    'temp': [59, 22, -10, 38, 20, 40, 38, 47, 20, 15, 13, 44, 57, 32, 38]
})
df.head()

temp
0    59
1    22
2   -10
3    38
4    20

In [102]:
# Можно задать свои границы диапазона и названия категорий
# Если планируется три категории, то границ должно быть на одну больше - 
#   так задаются диапазоны для категорий
df['temp_cat'] = pd.cut(
    x=df['temp'],
    bins=[-10, 10, 25, 60],
    labels=['low', 'medium', 'high'],
    # Флаг, чтобы самое левое значение границы входило в первый диапазон
    include_lowest=True
)
df.head()

temp temp_cat
0    59     high
1    22   medium
2   -10      low
3    38     high
4    20   medium

In [103]:
df['temp_cat'].dtype

CategoricalDtype(categories=['low', 'medium', 'high'], ordered=True)

In [104]:
# Можно не задавать имена категориям, тогда он сам их назовет
result_after_cut = pd.cut(
    x=df['temp'],
    bins=[-10, 10, 25, 60],
    include_lowest=True
)
# Взглянем на имена
result_after_cut.unique()

[(25.0, 60.0], (10.0, 25.0], (-10.001, 10.0]]
Categories (3, interval[float64]): [(-10.001, 10.0] < (10.0, 25.0] < (25.0, 60.0]]

In [105]:
# Можно не задавать границы, лишь количество категорий - 
#   разделение будет на категории с одинаковой шириной диапазонов
result_after_cut = pd.cut(
    x=df['temp'],
    bins=3
)
result_after_cut.unique()

[(36.0, 59.0], (13.0, 36.0], (-10.069, 13.0]]
Categories (3, interval[float64]): [(-10.069, 13.0] < (13.0, 36.0] < (36.0, 59.0]]

In [106]:
# Task 8 
df = pd.DataFrame({
    'quality': [ 7, 67, 21, 38,  2, -2, 79, 22,  5, 31, 77, 72, 23, 64, 99]
})
df.head()

quality
0        7
1       67
2       21
3       38
4        2

In [111]:
df['q_cat'] = pd.cut(
    x=df['quality'],
    bins=[0, 20, 45, 85, 100],
    labels=['bad', 'medium', 'good', 'excellent'],
    include_lowest=True
)
df.head()

quality   q_cat
0        7     bad
1       67    good
2       21  medium
3       38  medium
4        2     bad

In [112]:
df = pd.DataFrame([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [np.nan, np.nan, np.nan]],
                  columns=['A', 'B', 'C'])
df

A    B    C
0  1.0  2.0  3.0
1  4.0  5.0  6.0
2  7.0  8.0  9.0
3  NaN  NaN  NaN

In [113]:
# Получим значения минимумов и средних по всем колонкам
# Принцип аналогичен операциям в numpy - 
#   для агрегации по колонка операция должна пройти по рядам,
#   соответсвенно, axis='rows'
df.aggregate(['min', 'mean'], axis='rows')

A    B    C
min   1.0  2.0  3.0
mean  4.0  5.0  6.0

In [114]:
# Зададим правила агрегации для каждой колонки
# Операции можно задавать строками или функциями numpy
df.aggregate({
    'A': ['sum', 'min'],
    'B': ['max', 'min'],
    'C': [np.sum, np.mean],
})

A    B     C
max    NaN  8.0   NaN
mean   NaN  NaN   6.0
min    1.0  2.0   NaN
sum   12.0  NaN  18.0

In [115]:
# Task 9
df = pd.DataFrame(
    ([1, 2, 3], [4, 5, 6], [7, 8, 9]), 
    columns=['x1', 'x2', 'x3'])
df

x1  x2  x3
0   1   2   3
1   4   5   6
2   7   8   9

In [119]:
df.aggregate(
    np.mean, axis='columns'
)

0    2.0
1    5.0
2    8.0
dtype: float64

In [120]:
data = [
    [1, 4.7, 60],
    [3, 4.5, 45],
    [4, 4.8, 40],
    [1, 4.9, 58],
    [2, 4.1, 50],
    [2, 4.2, 49],
    [2, 4.4, 49],
    [3, 4.9, 46],
    [4, 4.3, 33],
]

stud_df = pd.DataFrame(data, columns=['Grade', 'Test_Mark', 'Time'])
stud_df

Grade  Test_Mark  Time
0      1        4.7    60
1      3        4.5    45
2      4        4.8    40
3      1        4.9    58
4      2        4.1    50
5      2        4.2    49
6      2        4.4    49
7      3        4.9    46
8      4        4.3    33

In [121]:
gr_stud_df = stud_df.groupby(by='Grade')

# Тип результата - pd.DataFrameGroupBy
print(type(gr_stud_df))

# Таким образом увидим словарь:
#   Ключи - названия групп
#   Значения - индексы из данных для группы
gr_stud_df.groups

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>


{1: [0, 3], 2: [4, 5, 6], 3: [1, 7], 4: [2, 8]}

In [122]:
gr_stud_df.agg('mean')

Test_Mark       Time
Grade                      
1       4.800000  59.000000
2       4.233333  49.333333
3       4.700000  45.500000
4       4.550000  36.500000

In [123]:
# Более сложный вариант - найдем средние и минимальные время и оценку 

gr_stud_df.agg(['mean', 'min'])

Test_Mark            Time    
           mean  min       mean min
Grade                              
1      4.800000  4.7  59.000000  58
2      4.233333  4.1  49.333333  49
3      4.700000  4.5  45.500000  45
4      4.550000  4.3  36.500000  33

In [124]:
# Или зададим правила для каждого признака по отдельности

res = gr_stud_df.agg({
    'Test_Mark': ['mean', 'min'],
    'Time': ['min']
})

print(type(res))
res

<class 'pandas.core.frame.DataFrame'>


Test_Mark      Time
           mean  min  min
Grade                    
1      4.800000  4.7   58
2      4.233333  4.1   49
3      4.700000  4.5   45
4      4.550000  4.3   33

In [125]:
# Для обращения к данным просто используем несколько индексов, 
#   так как это DataFrame
res['Test_Mark']['mean']

Grade
1    4.800000
2    4.233333
3    4.700000
4    4.550000
Name: mean, dtype: float64

In [126]:
# Task 10
df = pd.DataFrame({
    'x1': np.random.randint(10, 100, size=(200, )),
    'x2': np.random.choice(['low', 'high', 'medium'], size=(200, )),
    'x3': np.random.randint(-20, 30, size=(200, )),
})
df.head()

x1      x2  x3
0  38  medium   7
1  75  medium -12
2  98  medium  28
3  16     low   3
4  61     low   1

In [132]:
df.groupby(by='x2').agg(['median', 'max'])

x1         x3    
       median max median max
x2                          
high     57.5  99    7.5  29
low      49.0  99    4.0  27
medium   62.0  98    6.0  28

In [133]:
import string

df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3'],
    index=list(string.ascii_uppercase)[:15]
)
df.head(3)

x1  x2  x3
A   9   8   8
B   5   2   4
C   0   9   6

In [134]:
# Для сохранения задается путь до файла
df.to_csv('my_first_file.csv')

In [136]:
df = pd.read_csv('my_first_file.csv', index_col=0)
df.head(3)

x1  x2  x3
A   9   8   8
B   5   2   4
C   0   9   6

In [138]:
# Task 11
df = pd.DataFrame(
    data=np.random.randint(0, 10, size=(15, 3)), 
    columns=['x1', 'x2', 'x3'],
    index=list(string.ascii_uppercase)[:15]
)
df.head(3)

# TODO - сохранить в файл no_index.csv без индексов
df.to_csv('no_index.csv', index=False)

In [142]:
# Task 12 
df = pd.DataFrame(
    {
        'Name': ['Lena', 'Alex', 'Bob'], 
        'work exp': [2.7, 4.5, 5.6],
        'age': [26, 25, 37],
        'colour': pd.Categorical(['grey', 'yellow', 'navy'])
    }
)
df.head()

Name  work exp  age  colour
0  Lena       2.7   26    grey
1  Alex       4.5   25  yellow
2   Bob       5.6   37    navy

In [143]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype   
---  ------    --------------  -----   
 0   Name      3 non-null      object  
 1   work exp  3 non-null      float64 
 2   age       3 non-null      int64   
 3   colour    3 non-null      category
dtypes: category(1), float64(1), int64(1), object(1)
memory usage: 307.0+ bytes


In [152]:
# Task 13
ds1 = pd.Series([1, 2, 3, 4, 5])
ds2 = pd.Series([4, 5, 6, 7, 8, 1, 9])

# TODO - выберите значения в ds1, которых нет в ds2: 
# [2, 3]
ds1[(~ds1.isin(ds2))]

1    2
2    3
dtype: int64

In [157]:
# Task 14
ds = pd.Series([2, 2, 2, 4, 4, 4, 3, 1, 1, 1, 1, 4])

# TODO - определите два наиболее частых значения в ряду (1, 4),
#           остальные замените значением 'Другое'
# ['Другое', 'Другое', 'Другое', 4, 4, 4, 'Другое', 1, 1, 1, 1, 4]
ds[~ds.isin((ds.value_counts().index[:2]))] = 'Другое'
ds

0     Другое
1     Другое
2     Другое
3          4
4          4
5          4
6     Другое
7          1
8          1
9          1
10         1
11         4
dtype: object

In [159]:
# Task 15
ds = pd.Series(['how', 'to', 'use', 'pandas?'])

# TODO - сделайте каждую первую букву заглавной с помощью Series.apply()
ds.apply(lambda x: x[0].upper() + x[1:])

0        How
1         To
2        Use
3    Pandas?
dtype: object

In [167]:
# Task 16
df = pd.DataFrame(
    np.random.randint(0, 4, size=(15, 3)), 
    columns=['x1', 'x2', 'x3']
)

# TODO - выберите те записи, которые имеют x1 равный 
#           максимальному значению в колонке x1
df[df['x1'] == df['x1'].max()]

x1  x2  x3
0    3   1   1
2    3   1   2
7    3   3   2
12   3   2   0

In [169]:
# Task 17
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')

# TODO - отобразите количество пропусков в данных по каждой колонке
df.isna().sum()

Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                6
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

In [173]:
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')

# TODO - заполните NaN в колонке Min.Price средним значением по этой колонке
# NOTE - после заполнения убедитесь, что в этой колонке нет пропущенных
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)

In [176]:
df['Min.Price'].isna().sum()

0

In [179]:
# Taask 18
df = pd.DataFrame(np.random.randint(0, 10, size=(5, 6)), columns=list('fbecda'))

# TODO - получите фрейм с отсортированными по именам колонкам (f e d c b a)
# NOTE - сортировка должна быть автоматической
df.sort_index(axis=1, ascending=False)

f  e  d  c  b  a
0  2  1  3  5  1  5
1  5  1  2  6  7  1
2  0  9  6  3  4  9
3  6  7  6  5  4  8
4  3  8  4  3  5  0

In [180]:
# Task 19 
df = pd.read_csv('https://raw.githubusercontent.com/Kail4eK/ml_edu/master/datasets/Cars93_miss.csv')

# TODO - отобразите запись с периодичностью во фрейме и определенные колонки

In [183]:
df.iloc[::20][['Manufacturer', 'Model', 'Type']]

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

In [184]:
ds = pd.Series(['how', 'to', 'use', 'pandas?'])

# TODO - создайте ряд, содержащий длины строк:
# 0    3
# 1    2
# 2    3
# 3    7
# dtype: int64
ds.apply(lambda x: len(x))

0    3
1    2
2    3
3    7
dtype: int64