In [20]:
import math 
import numpy as np 
import pandas as pd 
import random
from pulp import LpMaximize, LpProblem, LpStatus, lpSum, LpVariable

In [21]:
from collections import Counter

def get_bundle_vector(bundle, classes):
    vector = []
    for class_ in classes:
        if class_ in bundle:
            vector.append(Counter(bundle)[class_])
        else:
            vector.append(0)
    return vector

In [22]:
bundles = {
    'B1':["a", "b", "c"],
    'B2':["f", "h", "h"],
    'B3':["j", "j", "j"],
    'B4':["d", "e", "i"],
    'B5':["f", "f", "g"],
    'B6':["a", "e", "i"],
    'B7':["b", "c", "d"],
    'B8':["g", "i", "j"]
}

In [23]:
class_prices = np.ones((1, 10), dtype=np.int16)
classes = np.array(["a", "b", "c", "d", "e", "f", "g", "h", "i", "j"])

In [24]:
bundles_discounts = {
    'B1': 0.1,
    'B2': 0.2,
    'B3':0.25,
    'B4':0.05,
    'B5':0.15,
    'B6': 0.35,
    'B7': 0.1,
    'B8':0.33
}

In [25]:
discounts = {key: round(1 - val, 2) for key, val in bundles_discounts.items()}
discounts

{'B1': 0.9,
 'B2': 0.8,
 'B3': 0.75,
 'B4': 0.95,
 'B5': 0.85,
 'B6': 0.65,
 'B7': 0.9,
 'B8': 0.67}

In [41]:
bundle_discounts_arr = (1 - np.fromiter(bundles_discounts.values(), dtype=float)).reshape(8, 1)
bundle_discounts_arr

array([[0.9 ],
       [0.8 ],
       [0.75],
       [0.95],
       [0.85],
       [0.65],
       [0.9 ],
       [0.67]])

In [26]:
bundle_dict = {key: get_bundle_vector(val, classes) for key, val in bundles.items()}
bundle_dict

{'B1': [1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
 'B2': [0, 0, 0, 0, 0, 1, 0, 2, 0, 0],
 'B3': [0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
 'B4': [0, 0, 0, 1, 1, 0, 0, 0, 1, 0],
 'B5': [0, 0, 0, 0, 0, 2, 1, 0, 0, 0],
 'B6': [1, 0, 0, 0, 1, 0, 0, 0, 1, 0],
 'B7': [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
 'B8': [0, 0, 0, 0, 0, 0, 1, 0, 1, 1]}

In [28]:
basket_product_number = np.random.random_integers(1, 20, size=(10, ))
basket_product_number

array([16, 12, 14,  7, 19,  6, 13,  9, 16,  5])

In [35]:
bundle_matrix = pd.DataFrame.from_dict(bundle_dict, orient='index').values
bundle_matrix

array([[1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 3],
       [0, 0, 0, 1, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 2, 1, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 1]])

In [29]:
# list of decision variables
bundle_lp = ['B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8']

# MAXIMIZE number of bundels 
# Create the model
model = LpProblem(name="Find max bundles problem", sense=LpMaximize)
# Initialize the decision variables
x_vars = LpVariable.dicts('x', bundle_lp, lowBound=0, cat='Integer')

# Z = sum(b_i)
model += lpSum([x_vars[i] for i in bundle_lp])
# Restriction 
# number of products in bundles must be less or equal with product number in basket 
for p in range(len(classes)):
    model += lpSum([bundle_dict[b][p] * x_vars[b] for b in bundle_lp]) <= basket_product_number[p]

model

Find_max_bundles_problem:
MAXIMIZE
1*x_B1 + 1*x_B2 + 1*x_B3 + 1*x_B4 + 1*x_B5 + 1*x_B6 + 1*x_B7 + 1*x_B8 + 0
SUBJECT TO
_C1: x_B1 + x_B6 <= 16

_C2: x_B1 + x_B7 <= 12

_C3: x_B1 + x_B7 <= 14

_C4: x_B4 + x_B7 <= 7

_C5: x_B4 + x_B6 <= 19

_C6: x_B2 + 2 x_B5 <= 6

_C7: x_B5 + x_B8 <= 13

_C8: 2 x_B2 <= 9

_C9: x_B4 + x_B6 + x_B8 <= 16

_C10: 3 x_B3 + x_B8 <= 5

VARIABLES
0 <= x_B1 Integer
0 <= x_B2 Integer
0 <= x_B3 Integer
0 <= x_B4 Integer
0 <= x_B5 Integer
0 <= x_B6 Integer
0 <= x_B7 Integer
0 <= x_B8 Integer

In [30]:
model.solve() 
print(f"Status: {LpStatus[model.status]}")


check_bundle = np.array([])

for x in model.variables():
    print(f"{x.name} = {x.varValue}")
    check_bundle = np.append(check_bundle, x.varValue)

Status: Optimal
x_B1 = 5.0
x_B2 = 4.0
x_B3 = 0.0
x_B4 = 0.0
x_B5 = 1.0
x_B6 = 11.0
x_B7 = 7.0
x_B8 = 5.0


In [49]:
# TODO: add arguments 
def get_bundle_cost(bun_num, bun_matrix, bun_discount_arr, cl_prices ):
    current_discounts = (bun_num > 0) * bun_discount_arr
    bundle_cost = np.asscalar(sum((bun_num * bun_matrix).dot(cl_prices.T) * current_discounts))
    return bundle_cost

In [65]:
# TODO: add arguments 
def get_no_bundled_cost(bun_num, bun_matrix, basket_pr_num, cl_prices):
    no_bundled_product_number = basket_pr_num - bun_num.T.dot(bun_matrix)

    not_enough_product_in_basket = ((basket_pr_num - bun_num.T.dot(bun_matrix))< 0).any()
    if not_enough_product_in_basket:
        print('ALARM! NOT ENOUGHT PRODUCTS IN BASKET')

    return np.asscalar(
        (basket_pr_num - bun_num.T.dot(bun_matrix)).dot(cl_prices.T)
    )

In [66]:
# TODO: add arguments 
def get_total_cost(bun_num, bun_matrix, bun_discount_arr, cl_prices, basket_pr_num):
    return round(get_no_bundled_cost(bun_num, bun_matrix, basket_pr_num, cl_prices) + get_bundle_cost(bun_num, bun_matrix, bun_discount_arr, cl_prices), 2)

In [70]:
check_bundle = check_bundle.reshape(1, 8).T

check_cost = get_total_cost(check_bundle, bundle_matrix, bundle_discounts_arr, class_prices, basket_product_number)

print(f"Min cost of basket: {check_cost}")

Min cost of basket: 94.05


In [71]:
bun = np.zeros((8, 1))
cost_without_bundles = get_no_bundled_cost(bun, bundle_matrix, basket_product_number, class_prices)

print(f"Cost without bundles: {cost_without_bundles}")

Cost without bundles: 117.0
