In [1]:
import numpy as np

In [58]:
arr_1d = np.array([1, 2, 3])

print(f"1D array:\t{arr_1d}\n")
print(f"Data type inside array:\n{type(arr_1d)}\n")
print(f"Array shape:\t{arr_1d.shape}\n")
print(f"The first element: {arr_1d[0]}\n")
print(f"The third element: {arr_1d[2]}\n")
print(f"The last element: {arr_1d[-1]}")

1D array:	[1 2 3]

Data type inside array:
<class 'numpy.ndarray'>

Array shape:	(3,)

The first element: 1

The third element: 3

The last element: 3


In [59]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(f"2D array (matrix):\n{arr_2d}\n")
print(f"Data type inside array:\n{type(arr_2d)}\n")
print(f"Array shape:\t{arr_2d.shape}")
print(f"Element of the first row and first column:\n{arr_2d[0, 0]}\n")
print(f"Element of the second row and the third column:\n{arr_2d[1, 2]}\n")
print(f"Element of the second row and the first column:\n{arr_2d[1, 0]}")

2D array (matrix):
[[1 2 3]
 [4 5 6]]

Data type inside array:
<class 'numpy.ndarray'>

Array shape:	(2, 3)
Element of the first row and first column:
1

Element of the second row and the third column:
6

Element of the second row and the first column:
4


In [6]:
np.ndarray((5, 3))

array([[2.2538437e-316, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000],
       [0.0000000e+000, 0.0000000e+000, 0.0000000e+000]])

In [7]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
np.full((3, 4), 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [10]:
np.eye(3, 2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [11]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

np.zeros_like(arr_2d)

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

np.ones_like(arr_2d)

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
np.random.random((2,2))

array([[0.55964829, 0.40418317],
       [0.56850836, 0.61742336]])

In [14]:
np.arange(start=1, stop=10, step=1.5)

array([1. , 2.5, 4. , 5.5, 7. , 8.5])

In [15]:
np.linspace(start=1, stop=2, num=10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [60]:
arr = list(range(1, 11))
print(f"Row vector: {arr}\n")
print(f"The first element: {arr[0]}\n")
print(f"The last second element: {arr[-2]}\n")
print(f"The sixth element: {arr[5]}")

Row vector: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

The first element: 1

The last second element: 9

The sixth element: 6


In [61]:
print(arr[2:8:2])

[3, 5, 7]


In [20]:
print(arr[2:8])

[3, 4, 5, 6, 7, 8]


In [21]:
print(arr[8:2:-1])

[9, 8, 7, 6, 5, 4]


In [22]:
print(arr[2:])
print(arr[:8])

[3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8]


In [23]:
print(arr[2::2])
print(arr[:8:3])

[3, 5, 7, 9]
[1, 4, 7]


In [24]:
new_arr = list(range(1, 11))

new_arr[1:5] = arr[:4]
print(new_arr)

[1, 1, 2, 3, 4, 6, 7, 8, 9, 10]


In [26]:
# Task 1 
print(arr)
print(arr[:5:-2])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10, 8]


In [27]:
# Task 2 
data = list(range(10))
print(data)
print(data[::-1])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [118]:
# Task 3
data = list(range(10))
print(data)
print(data[1:len(data)-2])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


AttributeError: 'list' object has no attribute 'shape'

In [64]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [65]:
# Получим вторую строку массива
print(arr[2])
print(arr[2, :])

[ 9 10 11 12]
[ 9 10 11 12]


In [66]:
# Получим первую колонку массива
print(arr[:, 1][..., None])

[[ 2]
 [ 6]
 [10]]


In [67]:
# Получить первые два элемента (первые две колонки) первого ряда
print(arr[1, :2])

[5 6]


In [69]:
# Можно повторять целые части массива
#   (но при этом должны соотноситься размерности)
# ndarray.copy() - функция копирования массива
# Копируем, чтобы не изменить оригинальный
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
new_arr = arr.copy()
print(f"original matrix:\n{arr}\n")

new_arr[2, :] = arr[1, :]
print(f"modified matrix:\n{new_arr}")

original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

modified matrix:
[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [70]:
# При этом, такая индексация - это новый массив со своей размерностью.
print(f"New matrix:\n{arr[:2, :2]}\n")
print(f"New shape: {arr[:2, :2].shape}")

New matrix:
[[1 2]
 [5 6]]

New shape: (2, 2)


In [37]:
# В качестве индексов можно также задавать другие массивы
# Получаем первую и последнюю колонки
print(arr[:, [0, -1]])

[[ 1  4]
 [ 5  8]
 [ 9 12]]


In [38]:
# И таким образом никто не заставляет писать в том же порядке индексы
# Перемешаем ряды
print(arr[[2, 0, 1], :])

[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [39]:
# Также, можно комбинировать способы задания
print(arr[[2, 0], [1, 3]])
# То же самое, только первая запись дает массив
print(arr[2, 1], arr[0, 3])

[10  4]
10 4


In [44]:
# Создаем список возможных индексов для рядов массива
print(f"arr shape: {arr.shape}")
row_indices = list(range(arr.shape[0]))
print(f"row indices:\n{row_indices}")

# Переворачиваем его
row_indices = list(reversed(row_indices))
print(f"reversed row indices:\n{row_indices}")

# Используем для индексации
print('----------------')
print(f"reversed arr:\n{arr[row_indices]}")

arr shape: (3, 4)
row indices:
[0, 1, 2]
reversed row indices:
[2, 1, 0]
----------------
reversed arr:
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [50]:
# Task 4 
data = np.random.randint(low=0, high=10, size=(5, 6))
print(f"original matrix:\n{data}\noriginal shape:{data.shape}\n")

cut_one_data = data[1:, 1:]
print(f"one side cutted matrix:\n{cut_one_data}\none side shape: {cut_one_data.shape}\n")

cut_both_data = data[1:len(data)-1, 1:len(data[0])-1]
print(f"cutted matrix:\n{cut_both_data}\ncutted matrix shape: {cut_both_data.shape}")

original matrix:
[[4 6 9 8 9 4]
 [3 2 8 2 4 7]
 [4 8 2 2 4 1]
 [0 4 9 2 7 8]
 [9 4 5 9 9 1]]
original shape:(5, 6)

one side cutted matrix:
[[2 8 2 4 7]
 [8 2 2 4 1]
 [4 9 2 7 8]
 [4 5 9 9 1]]
one side shape: (4, 5)

cutted matrix:
[[2 8 2 4]
 [8 2 2 4]
 [4 9 2 7]]
cutted matrix shape: (3, 4)


In [53]:
# Task 5 
data = np.random.randint(low=0, high=10, size=(3, 6))
print(f"original data:\n{data}\ndata shape: {data.shape}\n")

mixed_col_data = data[:, np.random.permutation(data.shape[1])]
print(f"column-mixed data:\n{mixed_col_data}\ncolumn-mixed data shape: {mixed_col_data.shape}")

original data:
[[2 3 0 1 0 4]
 [9 6 6 5 9 7]
 [4 1 3 5 8 5]]
data shape: (3, 6)

column-mixed data:
[[0 4 1 2 3 0]
 [9 7 5 9 6 6]
 [8 5 5 4 1 3]]
column-mixed data shape: (3, 6)


In [73]:
# Создадим массив без задания типа - тип будет определен автоматически
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"Default type of elements in matrix: {arr.dtype}")

Default type of elements in matrix: int64


In [74]:
# Изменим один элемент на вещественный
arr = np.array([[1.5, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"Default type of elements in matrix: {arr.dtype}")

Default type of elements in matrix: float64


In [75]:
# Зададим явно тип массива
# Хоть массив и содержит вещественные числа
# мы создаем массив целочисленных, что приводит
# к округлению
arr = np.array([[1.1, 1.6, 2.4], [-1.7, 2.6, -1.2]], dtype=int)
print(f"Original matrix:\n{arr}\n")
print(f"Type of element: {arr.dtype}")

Original matrix:
[[ 1  1  2]
 [-1  2 -1]]

Type of element: int64


In [76]:
# Создаем массив вещественных
arr = np.array([[1.1, 1.6, 2.4], [-1.7, 2.6, -1.2]])
print(f"Orignal matrix with float elements:\n{arr}\n")
print(f"Default type of elements: {arr.dtype}")
print('----------')
# Но в какой-то момент нам нужно привести массив к целочисленным
# Воспользуемся методом ndarray.astype()
arr = arr.astype(int)
print(f"Casted matrix:\n{arr}\n")
print(f"New type of elements: {arr.dtype}")

Orignal matrix with float elements:
[[ 1.1  1.6  2.4]
 [-1.7  2.6 -1.2]]

Default type of elements: float64
----------
Casted matrix:
[[ 1  1  2]
 [-1  2 -1]]

New type of elements: int64


In [78]:
# При этом попытки записать в целочисленный массив 
# вещественное число приводят к округлению
arr = np.array([[1.1, 1.6, 2.4], [-1.7, 2.6, -1.2]], dtype=int)
print(f"Orignal matrix:\n{arr}\n")

arr[0, 1] = 10.12
print(f"Attempt to use float values:\n{arr}")

Orignal matrix:
[[ 1  1  2]
 [-1  2 -1]]

Attempt to use float values:
[[ 1 10  2]
 [-1  2 -1]]


In [81]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"Original matrix:\n{arr}\n")

result = arr > 6
print(f"Bollean mask:\n{result}\n")
print(f"Type of elements in mask: {result.dtype}")

Original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Bollean mask:
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]

Type of elements in mask: bool


In [82]:
result_1 = arr > 6
result_2 = arr < 10
print(f"The first mask '> 6':\n{result_1}\n")
print(f"The second maks '< 10':\n{result_2}")

print('----------')
# Следующие две операции идентичны, но для второй скобки обязательны!
print(f"Logic AND:\n{result_1 & result_2}\n")
print(f"Logic AND:\n{(arr > 6) & (arr < 10)}")

The first mask '> 6':
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]

The second maks '< 10':
[[ True  True  True  True]
 [ True  True  True  True]
 [ True False False False]]
----------
Logic AND:
[[False False False False]
 [False False  True  True]
 [ True False False False]]

Logic AND:
[[False False False False]
 [False False  True  True]
 [ True False False False]]


In [85]:
# Task 6 
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(f"Original matrix:\n{arr}\n")

# TODO - определить, имеется ли в массиве хотя бы один элемент, 
#           отвечающий условию больше пяти и меньше восьми
print(f"Existance of element '> 5' and '< 8': {np.any((arr > 5) & (arr < 8))}")

Original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Existance of element '> 5' and '< 8': True


In [88]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# Получим маску и воспользуемся ею для индексации
mask = arr > 6
print(f"The mask '> 6':\n{mask}\n")
print(f"Elements from true-mask: {arr[mask]}")

The mask '> 6':
[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]

Elements from true-mask: [ 7  8  9 10 11 12]


In [90]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(f"Original matrix:\n{arr}\n")
print(f"Flattened matrix:\n{arr.flatten()}")

Original matrix:
[[1 2 3 4]
 [5 6 7 8]]

Flattened matrix:
[1 2 3 4 5 6 7 8]


In [91]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [93]:
# Сложение
print(f"Addition method 1:\n{x + y}\n")
print(f"Addition method 2:\n{np.add(x, y)}")

Addition method 1:
[[ 6.  8.]
 [10. 12.]]

Addition method 2:
[[ 6.  8.]
 [10. 12.]]


In [94]:
# Вычитание
print(f"Substraction method 1:\n{x - y}\n")
print(f"Substraction method 2:\n{np.subtract(x, y)}")

Substraction method 1:
[[-4. -4.]
 [-4. -4.]]

Substraction method 2:
[[-4. -4.]
 [-4. -4.]]


In [96]:
# Поэлементное умножение
print(f"Element-wise multiplication method 1:\n{x * y}\n")
print(f"Element-wise multiplication method 2:\n{np.multiply(x, y)}")

Element-wise multiplication method 1:
[[ 5. 12.]
 [21. 32.]]

Element-wise multiplication method 2:
[[ 5. 12.]
 [21. 32.]]


In [97]:
# Поэлементное деление
print(f"Element-wise division method 1:\n{x / y}\n")
print(f"Element-wise division method 2:\n{np.divide(x, y)}")

Element-wise division method 1:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]

Element-wise division method 2:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [98]:
# Вычисление корня каждого элемента
print(f"Element-wise square root:\n{np.sqrt(x)}")

Element-wise square root:
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [100]:
k = 1.5

print(f"Multiplication by constant:\n{k*x}")

Multiplication by constant:
[[1.5 3. ]
 [4.5 6. ]]


In [101]:
v = np.array([1, 2])

In [105]:
# Матричное умножение реализуется через оператор @ или функцию np.dot() 
# или метод ndarray.dot()
# Для умножения матрица-вектор

print(f"Matrix-vector multiplication @-method:\n{x @ v}\n")
print(f"Matrix-vector multiplication .dot-method:\n{x.dot(v)}\n")
print(f"Matrix-vector multiplication np.dot-method:\n{np.dot(x, v)}")

Matrix-vector multiplication @-method:
[ 5. 11.]

Matrix-vector multiplication .dot-method:
[ 5. 11.]

Matrix-vector multiplication np.dot-method:
[ 5. 11.]


In [103]:
# Двух векторов
w = np.array([3, 4])

print(f"Vector multiplication @-method:\n{w @ v}\n")
print(f"Vector-multiplication .dot-method:\n{w.dot(v)}\n")
print(f"Vector-multiplication np.dot-method:\n{np.dot(w, v)}")

Vector multiplication @-method:
11

Vector-multiplication .dot-method:
11

Vector-multiplication np.dot-method:
11


In [104]:
print(f"Matrix multiplication @-method:\n{x @ y}\n")
print(f"Matrix multiplication .dot-method:\n{x.dot(y)}\n")
print(f"Matrix multiplication np.dot-method:\n{np.dot(x, y)}")

Matrix multiplication @-method:
[[19. 22.]
 [43. 50.]]

Matrix multiplication .dot-method:
[[19. 22.]
 [43. 50.]]

Matrix multiplication np.dot-method:
[[19. 22.]
 [43. 50.]]


In [108]:
# Для транспонирования можно воспользоваться атрибутом ndarray.T
# или функцией np.transpose()
x = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Original matrix:\n{x}\n")
print(f"Shape of original matrix: {x.shape}")
print('--------')
print(f"Transpose matrix (np.transpose):\n{np.transpose(x)}\n")
print(f"Transpose matrix (.T):\n{x.T}\n")
print(f"Shape of transpose matrix: {x.T.shape}")

Original matrix:
[[1 2 3]
 [4 5 6]]

Shape of original matrix: (2, 3)
--------
Transpose matrix (np.transpose):
[[1 4]
 [2 5]
 [3 6]]

Transpose matrix (.T):
[[1 4]
 [2 5]
 [3 6]]

Shape of transpose matrix: (3, 2)


In [109]:
x = np.array([[1, 2, 3], [5, 4, 3]])
print(f"Matrix x:\n{x}")

Matrix x:
[[1 2 3]
 [5 4 3]]


In [110]:
# Возьмем среднее значение всего массива
print(f"Mean value of all matrix: {np.mean(x)}\n")
print(f"Mean value of all matrix: {np.mean(x, axis=None)}")

Mean value of all matrix: 3.0

Mean value of all matrix: 3.0


In [111]:
# Получим сумму значений всего массива
print(f"Sum of all matrix values: {np.sum(x)}\n")
print(f"Sum of all matrix values: {np.sum(x, axis=None)}")

Sum of all matrix values: 18

Sum of all matrix values: 18


In [112]:
# Получим среднее по каждому столбцу
print(f"Maen along each colimn: {np.mean(x, axis=0)}")

Maen along each colimn: [3. 3. 3.]


In [113]:
# Получим среднее по каждой строке
print(f"Mean along each row: {np.mean(x, axis=1)}")

Mean along each row: [2. 4.]


In [115]:
# Task 7 
data = np.random.randint(low=0, high=5, size=(3, 6))
print(f"Original matrix:\n{data}\n")

# TODO - вектор сумм элементов по каждому столбцу
print(f"Sum of each column: {np.sum(data, axis=0)}")

Original matrix:
[[3 1 1 2 3 1]
 [4 4 4 1 2 0]
 [1 1 0 0 0 3]]

Sum of each column: [8 6 5 3 5 4]


In [116]:
vec = np.arange(4)
mtrx = np.ones((3, 4))
print(f"Row-vector: {vec}\n")
print(f"Original matrix:\n{mtrx}")

Row-vector: [0 1 2 3]

Original matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [117]:
result = np.empty_like(mtrx)

for i_row in range(mtrx.shape[0]):
    result[i_row,:] = mtrx[i_row,:] * vec

print(f"Multiplication of vector by each row of matrix:\n{result}")

Multiplication of vector by each row of matrix:
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [120]:
# Функция np.tile() повторяет массив то количество раз и по тем осям,
#   которые заданы в аргументе reps
vec_m = np.tile(vec, reps=(3, 1))
print(f"Matrix with repetition from row-vector:\n{vec_m}\n")
print(f"Matrix multiplication:\n{vec_m * mtrx}")

Matrix with repetition from row-vector:
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]

Matrix multiplication:
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [121]:
# Умножение, используя броадкастинг
print(f"Broadcasting multiplication:\n{vec * mtrx}")

Broadcasting multiplication:
[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


In [128]:
x = np.ones((4, 1, 1))
y = np.random.randint(0, 5, size=(4, 3, 2))

print(f"x shape: {x.shape}\n")
print(f"y shape: {y.shape}\n")

print(f"Shape after broadcasting multiplication:\n{(x*y).shape}")

x shape: (4, 1, 1)

y shape: (4, 3, 2)

Shape after broadcasting multiplication:
(4, 3, 2)


In [129]:
x = np.ones((3, 1))
y = np.random.randint(0, 5, size=(4, 3, 2))

print(f"x shape: {x.shape}\n")
print(f"y shape: {y.shape}\n")

print(f"Shape after broadcasting multiplication:\n{(x*y).shape}")

x shape: (3, 1)

y shape: (4, 3, 2)

Shape after broadcasting multiplication:
(4, 3, 2)


In [130]:
x = np.ones((1, 3, 2))
y = np.random.randint(0, 5, size=(5, 1, 2))

print(f"x shape: {x.shape}\n")
print(f"y shape: {y.shape}\n")

print(f"Shape after broadcasting multiplication:\n{(x*y).shape}")

x shape: (1, 3, 2)

y shape: (5, 1, 2)

Shape after broadcasting multiplication:
(5, 3, 2)
